name: bank_kata
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.13.4-42.0.dev <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.1.2
  lints: ^1.0.0
  mockito: ^5.0.15
  test: ^1.16.0
dependencies: null
