// Mocks generated by Mockito 5.0.15 from annotations
// in bank_kata/test/statement_printer_test.dart.
// Do not manually edit this file.

import 'package:bank_kata/printer.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Printer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrinter extends _i1.Mock implements _i2.Printer {
  MockPrinter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void print(String? data) =>
      super.noSuchMethod(Invocation.method(#print, [data]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
